fix: we don't really care if maven.alphagame.dev fails on snapshot releases

diff --git a/.github/workflows/snapshot-release.yml b/.github/workflows/snapshot-release.yml
--- a/.github/workflows/snapshot-release.yml
+++ b/.github/workflows/snapshot-release.yml
@@ -38,7 +38,8 @@ jobs:
             SNAPSHOT: true
 
         - name: Publish snapshot to maven.alphagame.dev
-          run: ./gradlew publishSnapshotToReposilite
+          run: |
+            ./gradlew publishSnapshotToReposilite || echo "Snapshot publication failed, but continuing workflow"
           env:
             USERNAME: ${{ github.actor }}
             TOKEN: ${{ secrets.GITHUB_TOKEN }}
